version: '3'

services:

  postgres:
    image: postgres:13 # Stuck with this version until I find out why Postgres:13 is being demanded (local issue)
    container_name: postgres-dev
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: